### ISSUE TITLE
Issue in Exercise 1 Task 4

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#100]
In exercise 1 task 4 step 10, The Github action workflow is failing with an error: `buildx call failed with: error: failed to solve: unexpected status: 403 Forbidden`.  Similarly, content-api and content-init workflows are also failing. 

In exercise 3 task 2 step 8, docker-publish workflow is also failing. Please look into it. 

![image](https://user-images.githubusercontent.com/81952290/150125385-183d0c34-8b85-4295-b4f2-e36ffc087382.png)

**Comment by saimachi** [comment]
Hi @Shivashant25,

Thanks for bringing this to our attention. In my testing, I observed that replacing `docker.pkg.github.com/[USERNAME]/[REPOSITORY]` with `ghcr.io/[USERNAME]` as the target registry worked. 

To observe the necessary changes, you can refer to [my fork](https://github.com/saimachi/MCW-Continuous-delivery-in-Azure-DevOps). However, please note that I am continuing to test this lab, so I will be working on updating the lab content to reflect the container registry URL change.

**Comment by DawnmarieDesJardins** [comment]
Closing issues as resolved with merge of PR #101
