### ISSUE TITLE
Issue in Exercise 1 Task 4

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#102]
In Exercise 1> Task 4>, All the workflow files(fabrikam-web.yml, fabrikam-api.yml, and fabrikam-init.yml) are failing with an error mentioned in the image below. Please look into this.

![image](https://user-images.githubusercontent.com/81952290/152606580-07e1bba0-4778-4b1d-9668-a9ba937b0938.png)

**Comment by timahenning** [comment]
Fixed with PR #104 .

**Comment by Karthikkc123** [comment]
In [Exercise-01 Task-04 Step-10](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md), GitHub action for fabrikam-web.yml workflow is getting failed with the following error. 

`Error: signing [ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060]: parsing reference: could not parse reference: ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060
main.go:46: error during command execution: signing [ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060]: parsing reference: could not parse reference: ghcr.io/Karthikkc123/mcw-continuous-delivery-lab-files/fabrikam-web@sha256:cc64700e3397bd056c1028a7db99c06443a97662893f54c27f9f893f650f9060`

Please find the screenshot below for your reference:
![image](https://user-images.githubusercontent.com/83394010/155140796-0d0215df-18d1-4157-b427-0697a12e88b3.png)

Instruction in Exercise-01 Task-01 Step-07 is not clear. For **REGISTRY**, should we use **ghcr.io/${{ github.actor }}** or **ghcr.io/Githubaccountname/Githubreponame**? Please suggest on this.

We have multiple workshops scheduled for this lab. Please check this as soon as possible.
