### ISSUE TITLE
flw53r8k5

### ISSUE THREAD

**Issue by NAPADAI** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#117]
**Describe the bug**

**HOL or Workshop Document**
If it is a specific document, provide a the name.

**Time Frame Needed**
Specific event or activity that would benefit from fixing this bug

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment  (please provide specifics if appropriate) :**
 - OS: [e.g. Wndows, Linux, iOS]
 - Browser [e.g. edge, chrome, safari and version
 - Device: [e.g. PC, iPhone6]

**Additional context**

**Comment by DawnmarieDesJardins** [comment]
@NAPADAI 
Hello.  Did you mean to open this issue, this only contains the template information.  Please let us know how we can help you.

**Comment by DawnmarieDesJardins** [comment]
Closing this issue as it seems to be opened in error.  If not, please re-open and provide details of where you're having trouble.
