### ISSUE TITLE
Rebranding to Azure DevOps

### ISSUE THREAD

**Issue by hkamel** [Microsoft/MCW-Continuous-delivery-in-Azure-DevOps#12]
Should we consider rebranding the workshop title and its relevant document to Azure DevOps instead of VSTS?

**Comment by jschluchter** [comment]
We'll work to rebrand this over the next few weeks.

**Comment by snpdev** [comment]
Hi. I see a `jan-2019-update` branch, but it appears in sync with master, i.e. no Azure DevOps branding updates. I assume this `jan-2019-update` branch is in place for review of the branding updates, prior to a merge into master. If this is the case, would it be possible to push the pending Azure DevOps branding updates to this branch in the coming days? I would like to use this workshop for a January training engagement, and preferably with the Azure DevOps branding.

Thanks - Mike

**Comment by crpietschmann** [comment]
@snpdev I recommend using the master branch for delivery. This brand is for the coming updates that are being worked on and isn’t ready for release yet.

We appreciate your interest!

**Comment by snpdev** [comment]
Thanks for the status update @crpietschmann. I stepped through the workshop today using the master branch. It's solid. Until the branding update is ready, I will recommend to my trainees that New Navigation be turned off from the Preview features menu. Even with New Navigation off, there are a handful of UI differences (e.g. "Repos" in lieu "Code"), but these are manageable. I'll keep an eye out for the next release.

**Comment by DawnmarieDesJardins** [comment]
@snpdev @sdavis3 @Jeff-Opsgility 

Hi Mike - When is your delivery? I'd love to get this completed for you in time for it.

Shane - I see you've been working on Michael's feedback.  Is the update ready for QC/merge?
 
Dawnmarie

**Comment by snpdev** [comment]
@DawnmarieDesJardins. Workshop is scheduled for Thursday, Jan 24. Perhaps this is too soon to accommodate your QC/merge requirements?

**Comment by sdavis3** [comment]
@DawnmarieDesJardins Yes, it is ready for review and merge.

**Comment by DawnmarieDesJardins** [comment]
Thanks Sean!
@snpdev - We need a SME/lead review before a QC/merge so we may not make your 1/24 workshop, sorry.  I will keep a close eye on reviews and let you know when it's done.
