### ISSUE TITLE
Misplaced instructions at Ex1 Task4 Steps 1-4

### ISSUE THREAD

**Issue by manasvin** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#121]
Instructions to create a secret CR_PAT  (Ex1 Task4 Steps 1-4) are not meant for Exercise 1 but need to be placed in Exercise 2 which is where they are eventually used but not used anywhere before.

**Comment by DawnmarieDesJardins** [comment]
@hatboyzero @timahenning 
Hello.  Any update on this and issue #120 for us please?

**Comment by sadukie** [comment]
After reviewing the lab, the CR_PAT in GitHub secrets isn't used until Exercise 3, Task 2, Step 6.  

Exercise 2 uses the environment variable set in Exercise 2, Task 2, Step 1.

I will incorporate the CR_PAT steps in Exercise 3, Task 2.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #122
