### ISSUE TITLE
re-open #120 Multiple workflows caused by instruction - Exercise 1, Task 4, Step 11

### ISSUE THREAD

**Issue by manasvin** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#123]
Issue not fixed so please reopen

#120 Multiple workflows caused by instruction - Exercise 1, Task 4, Step 11

**Comment by DawnmarieDesJardins** [comment]
Closing this issue.  Issue #120 was reopened, and all necessary documentation is there.
