### ISSUE TITLE
Couldn't create GitHub Secret with Name (GITHUB_TOKEN)

### ISSUE THREAD

**Issue by karthikkc24** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#124]
In [Exercise-1 Task-4](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-4-build-automation-with-github-registry), while creating Publish Docker Container workflow for fabrikam-web.yml, fabrikam-api.yml & fabrikam-init.yml. We were facing a sign-in and 403 Forbidden error that led to failure of workflow file at line number 61, code included with Secret name as following **password: ${{secrets.GITHUB_TOKEN}}**.Where we are creating the Secret with name **GITHUB_TOKEN** and encountered the below error.

![image](https://user-images.githubusercontent.com/83394010/162461617-e5c85b86-3ff4-4cb3-a74f-e29661685e5b.png)

![image](https://user-images.githubusercontent.com/83394010/162460464-a09de66a-5e74-495f-bc37-8711b39cdc42.png)

![image](https://user-images.githubusercontent.com/83394010/162457907-9f7fb9fe-e4ae-4022-b8c1-04bdb74a028b.png)

After creating a PAT token with name **CR_PAT** and updated it in the workflow file at line number 61 with **password: ${{secrets.CR_PAT}}** workflow got succeed.

![image](https://user-images.githubusercontent.com/83394010/162462920-331c5194-a5f7-4b02-b6c2-638ce034121f.png)

Can you please review and make changes accordingly.

**Comment by karthikkc24** [comment]
@sadukie Glad to hear that ! Will be waiting to hear back from you. Thank you and have a great weekend.

**Comment by DawnmarieDesJardins** [comment]
Closing with merge of PR #125
