### ISSUE TITLE
Need to update Visual Studio Team Services part in lab guide.

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-Continuous-delivery-in-Azure-DevOps#16]
1. Now VSTS is Azure DevOps. Please update the lab guide accordingly from [Exercise 2.1](https://github.com/Microsoft/MCW-Continuous-delivery-in-VSTS-and-Azure/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20VSTS%20and%20Azure.md#task-1-create-visual-studio-team-services-account). 
1. Whenever there is new signup for Azure DevOps(VSTS). New interface comes up for that signup. 
1. Please let me know in case of any question.
![snag_1ea7a08d](https://user-images.githubusercontent.com/27498287/48852148-bdead900-edd2-11e8-9e66-f47f77ab2964.png)

**Comment by fasalzaman** [comment]
Any updates on this issue?

**Comment by DawnmarieDesJardins** [comment]
SME review for the current update is due by EOD today.  Your issue will be taken into consideration with SME comments for the update.
