### ISSUE TITLE
December Update - Author Suggestions

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-Continuous-delivery-in-Azure-DevOps#17]
Use the same scenario but to use Azure DevOps to solve the customer problem.

**Comment by danielshue** [comment]
In addition to updating to Azure DevOps, updating the screen shots would make sense as well.

**Comment by mwasham** [comment]
Agreed - the intent is to completely rewrite the solution in the WDS and the hands-on lab using Azure DevOps as the solution.

**Comment by DawnmarieDesJardins** [comment]
Suggestion received via email:

I would suggest change in the name as VSTS is no longer there since last Ignite announcement - September 2018, now it’s called Azure DevOps Services 😊.

Thanks,
 
Mariusz Borna

**Comment by waltermyersiii** [comment]
Yes, well aware of that.

**Comment by danielshue** [comment]
I would also like to see some development of Manual Testing (Test Plans) in Azure DevOps.

**Comment by dmckinstry** [comment]
@danielshue - Would Test Plans be better handled in a HOL (like this: https://www.azuredevopslabs.com/labs/azuredevops/testmanagement/) or do you think it makes sense in an MCW?  I know our enterprise customers still actively do manual testing but is that what we want included/recommended in the broader DevOps discussion.  (I am legitimately interested in your opinion.)

**Comment by dburnison** [comment]
Quick observations about the slides:
Slide 27: Replace "MSDN subscriptions" with "Enterprise DevTest Subscriptions". 
Slide 31: "complete" should be "compete"

Hands On Lab:
In addition to the above mentioned pre-deployment approval I would add a post deployment approval to the Dev environment. 

I know we don't want to make the lab too long but we could either: 
1. Show how to do a Pull request build or, 
2. Demonstrate traceability from requirement through to deployment. 

1. Do a Pull Request build
- Before Exercise 6
  - Clone the build definition and name it "TailspinToys-PR".
  - Remove the "Publish Build Artifacts" task from "TailspinToys-PR".
  - Note that we could add tasks to perform security checks, etc. at this point.
  - Add a branch policy that runs the new build
- As part of Exercise 6, before "Task 4: Approve and complete a pull request"
  - View the pull request build results to verify that the tests have passed

2. Demonstrate the traceability: 
- Before "Task 1: Create a new branch" in Exercise 6
  - Go to the Kanban Board and add a User Story that says "Change the page heading to 'Tailspin Toys'. Change the work item's state to "Active".
- Create the branch from the user story to connect the branch to the requirement.
- After the build and first release complete:
  - Go back to the Kanban Board to see that the user story is Closed. 
  - Open the user story and look under "Development" to see the links to the Git commits and the CI build.
  - Click on the CI build. 
    - Go to "Summary" page
      - Review the "Associated changes" and "Linked Work Items"
      - click on "View all" under "Deployments" to see which environments now have the code change. 
By adding the work item and changing where we create the branch we can also highlight the tracebility from Azure Boards -> Azure Repos -> Azure Pipelines (Build) -> Azure Pipelines (Release)

**Comment by DawnmarieDesJardins** [comment]
Please include open issues #12 & #16 in this update review and close out as appropriate when update is complete.  Thanks!

**Comment by DawnmarieDesJardins** [comment]
@mwasham @hopero929 @waltermyersiii 
Hi Michael,
SME feedback due EOD 12/18.  Please move update forward with the feedback received above.  When a PR is ready for SME review, assign it to me and I'll send out the notifications.
Thanks, Dawnmarie

**Comment by dburnison** [comment]
> @danielshue - Would Test Plans be better handled in a HOL (like this: https://www.azuredevopslabs.com/labs/azuredevops/testmanagement/) or do you think it makes sense in an MCW? I know our enterprise customers still actively do manual testing but is that what we want included/recommended in the broader DevOps discussion. (I am legitimately interested in your opinion.)

I don't think the HOLs and these workshops are mutually exclusive. Unless, we are saying that we should first consider using the HOLs and then only use a MCW like this when we want to provide a broader experience since the HOLs only focus on one component at a time. I still get asked about Azure Test Plans, in fact I am providing an Azure Test Plans overview tomorrow (12/20) for Underwriters Labs and Wellmark just verbally committed to switching from Micro Focus ALM to Azure Test Plans.

**Comment by dmckinstry** [comment]
@dburnison - This is more about the scope and purpose.  MCWs have a higher investment and cover more area.  HOLs tend to be more targeted.  I have a hard time thinking about a good general purpose whiteboard session on test plans.  But it is easy to have an HOL.  I also think many QA groups who would use Test Plans are opinionated about how they work - they want to know how the tools work more than how to structure their tests.  (i.e., again an HOL target more than an MCW.)
