### ISSUE TITLE
Improve task "Download the exercise files"

### ISSUE THREAD

**Issue by snpdev** [Microsoft/MCW-Continuous-delivery-in-Azure-DevOps#20]
Thanks for the [Azure DevOps branding update](https://github.com/Microsoft/MCW-Continuous-delivery-in-Azure-DevOps/pull/19). I am skimming the instructions now to see what has changed.

I have a suggestion to improve the "Download the exercise files" task. Right now, this is a step in "Task 3: Validate connectivity to Azure". IMO, it should be its own task, i.e. Step 4.

**Comment by DawnmarieDesJardins** [comment]
Labeling this issue as an enhancement - to be resolved in the scheduled May 2019 test/fix.
