### ISSUE TITLE
Inconsistent UI/UX for build pipeline

### ISSUE THREAD

**Issue by snpdev** [Microsoft/MCW-Continuous-delivery-in-Azure-DevOps#21]
My user experience for "Exercise 3: Create Azure DevOps build pipeline" is different from the HOL instructions.

When I click the **New pipeline** button, this is what I see:

![image](https://user-images.githubusercontent.com/1825479/51803043-5b70e780-221e-11e9-98a8-47f3a4fc97ca.png)

Assuming I continue, the next steps is:

![image](https://user-images.githubusercontent.com/1825479/51803090-e7830f00-221e-11e9-9d06-d76415a2ad2c.png)

With the result being the **visual designer**, not a YAML file:

![image](https://user-images.githubusercontent.com/1825479/51803076-b1de2600-221e-11e9-8eae-5775617a6933.png)

I can click View YAML, but the YAML is not quite the same as in the HOL instructions.

**Comment by sdavis3** [comment]
This could be due to some preview features rolling out to various instances. Would you be willing to turn on "New YAML pipeline creation experience" so see if it matches the flow correctly? You can find it by clicking on your profile in the top right, then selecting Preview features, then navigating all the way to the bottom.

**Comment by snpdev** [comment]
Bingo! "New YAML pipeline creation experience" was disabled. I didn't even notice it hiding at the bottom of the Preview features menu (Figure 1). In the instructions, please point out the "New YAML pipeline creation experience" requirement. (When I deliver the workshop, I'll direct the users' attention to the "Use the visual designer" link so they aware of this option.)

I see a UI distinction in the YAML pipeline wizard relative to the images in the instructions. The wizard steps are positioned to the left of the configuration dialogs, not above, and the labels have changed (Figure 2). 

**Figure 1**
![image](https://user-images.githubusercontent.com/1825479/51844861-51192100-22e4-11e9-818a-eb783094bedd.png)

**Figure 2**
![image](https://user-images.githubusercontent.com/1825479/51845082-d0a6f000-22e4-11e9-9fa9-856c34dfe02f.png)

**Comment by wely** [comment]
> This could be due to some preview features rolling out to various instances. Would you be willing to turn on "New YAML pipeline creation experience" so see if it matches the flow correctly? You can find it by clicking on your profile in the top right, then selecting Preview features, then navigating all the way to the bottom.

Hi guys, if that's the case, shall we include this step to the HOL?
