### ISSUE TITLE
No ASP.NET project in the repo

### ISSUE THREAD

**Issue by vermegi** [Microsoft/MCW-Continuous-delivery-in-Azure-DevOps#22]
When executing Exercise 5, the release pipeline fails, since there is only an ARM template in the git repo, there is no actual ASP .NET project present. I read through the previous steps again, but I don't think I missed creating this. So this additional step of creating an ASP .NET web app project in Visual Studio and checking this in as well into the repo is still needed.

**Comment by sdavis3** [comment]
Be sure to review the "Before the HOL.html" document located at [https://github.com/Microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/HTMLLINKS.md](https://github.com/Microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/HTMLLINKS.md). In Task 3, you download the sample project that contains the ASP.NET solution.

**Comment by DawnmarieDesJardins** [comment]
Issue resolved. Closing.
