### ISSUE TITLE
Threshold values = null

### ISSUE THREAD

**Issue by Pungbjorn** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#26]
Some threshold values were created with null in Visual Studio.
I had to change them for template deployment to work.
"threshold": NULL -> "threshold": 80.0

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Thanks!
This workshop will be going through a test/fix in April.  Bringing your issue to their attention to resolve.

**Comment by sdavis3** [comment]
@Pungbjorn I'm not able to reproduce this behavior. Do you have any screenshots demonstrating this?
