### ISSUE TITLE
Content Update - Technology Stack

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#30]
Currently, the entire tech stack is outdated, using older stack. I suggest we update it to the following to have the latest capabilities and open source stack on the market:

- Angular frontend plus asp.net core API backend
- PostgreSQL backend to demonstrate a DB other than SQL Database on Azure.

### Affected
- The whiteboard and HOL would both be affected. 
- Dev environment would change to use Visual Studio Code and dotnet compile (HOL prereqs)

References:
#29

**Comment by sdavis3** [comment]
I’m in general agreement with this ask…specifically around the Angular and ASP.NET Core request. I could go either way on the PostreSQL backend request, but I do agree moving away from SQL Database for Azure would be a welcome change.

**Comment by waltermyersiii** [comment]
Yes, move to PostgreSQL on backend. Becoming more popular, especially for high-scale, distributed scale out.

**Comment by waltermyersiii** [comment]
Also agree on Angular or React front end.

**Comment by DawnmarieDesJardins** [comment]
Closing as address in Aug 2019 update
