### ISSUE TITLE
Content Update - Automate Before HOL

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#31]
the entire prerequisite steps should be automated with scripts and ARM templates in the MCW, and executed in Cloud Shell.

#### Objectives:
- speed up the prereq process for all
- demonstrate scripting and ARM templates
- reduce dependency on screenshots

References
#29

**Comment by waltermyersiii** [comment]
Yes, we're planning this for all updates where applicable. ;-)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as address in Aug 2019 update
