### ISSUE TITLE
Content Update - Incorporate Azure DevOps Artifacts

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#32]
A more realistic scenario is that development would build and then package binaries to an Artifact repository. This would represent the version of the app and would be deployed to App Services, for example.

### Objectives
- Incorporate Artifacts to expose this feature
- Increase the realism of the deployment

References
#29

**Comment by DawnmarieDesJardins** [comment]
Closing issue as address in Aug 2019 update
