### ISSUE TITLE
Content Update - Multi-stage YAML Pipelines

### ISSUE THREAD

**Issue by sdavis3** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#33]
Update content to move away from visual editor and leverage the unified YAML experience.

**Comment by kevinhillinger** [comment]
I agree that this is going to be a much better experience where possible. Additionally, this allows for direct sample/reference YAML to be placed within the MCW itself as scaffolding.

**Comment by sdavis3** [comment]
Holding off on this one until the next update for the release approval functionality (using YAML) to go GA.

**Comment by DawnmarieDesJardins** [comment]
Closing issue - addressed in June 2020 update with PR #65
