### ISSUE TITLE
Preview feature update

### ISSUE THREAD

**Issue by cloudmelon** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#34]
Hi Preview feature in Azure DevOps has been updated : 

Latest : 
![image](https://user-images.githubusercontent.com/4621560/61999674-ea27c980-b0c6-11e9-9892-092f906376ca.png)

Didn't find : 
****
![image](https://user-images.githubusercontent.com/4621560/61999691-1b07fe80-b0c7-11e9-9fd8-94f6ab6f1149.png)

I'll update the content accordingly as well :)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as addressed in Aug 2019 update
