### ISSUE TITLE
Alternative option to add an Azure Resource manager service connection 

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#38]
Lab step details: Exercise 4 (Create Azure Devops release pipeline) Task 1,Step 9
There is an issue in **Configuring Azure Service Connection** i.e after clicking Authorize, there is an error like **Failed to set Azure permission & Ensure to apply permission at the Subscription level to get Authorized to Azure** , which can't be provided for this lab. So, we request you to add the steps about the  drop down option i.e **Advanced options** and then they’ll need to select subscription / existing resource group which is the alternate solution to get authorized to Azure service connection. So they do not need subscription level permission for this.
Please find the attached files. 
![IMG_20190904_181303](https://user-images.githubusercontent.com/55180169/64678649-a2eb7180-d497-11e9-8b31-bb10dc056237.jpg)
![advancedoptions](https://user-images.githubusercontent.com/55180169/64678794-f1007500-d497-11e9-831d-162a1039e27e.jpg)
![step3](https://user-images.githubusercontent.com/55180169/64679736-f65ebf00-d499-11e9-8267-c6017f0cc89b.PNG)

**Comment by sdavis3** [comment]
In the situation where a student doesn't have subscription level permissions, you are correct, they would see this permission error. I'll defer to @waltermyersiii as to if he wants to include this change in a future update.

**Comment by waltermyersiii** [comment]
Yes, do include.
