### ISSUE TITLE
Az DevOps authentication through Azure Shell

### ISSUE THREAD

**Issue by clementlrms** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#42]
Hi, 

is there specific guidelines to authenticate to Azure DevOps using Azure Shell ?
In task 2, this is required to sync up local repo (Azure Shell) with Azure DevOps Project.
Work around is to use VS code + PAT with Git Bash for Windows, but I did not find a way to do it using Azure Shell. 
I appreciate your feedback.

**Comment by snpdev** [comment]
I have the same problem as @clementlrms at Exercise 2, Task 2, bullet 6.

```
michael@Azure:~/mcw/tailspintoysweb$ git push -u origin --all
Password for 'https://<myorg>@dev.azure.com':
```
IMHO, the workshop should reflect the way a developer would probably peform this activity, i.e. using an IDE (e.g. Visual Studio 2019 or VS Code) with git integration, or run git commands from a CLI.

**Comment by paulopsgility** [comment]
@clementlrms @snpdev Thanks for the feedback, we are looking into this. We'll respond here as soon as we are done investigating this. 

Thanks
Paul

**Comment by paulopsgility** [comment]
We will pick this up on the next test/fix
