### ISSUE TITLE
You do not have permissions to create resource groups under subscription

### ISSUE THREAD

**Issue by masyanru** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#44]
... and this is the main problem.
When I've opened the step-by-step guide the first step was "From the Azure web portal, launch the Azure Cloud Shell" and you can't do this because you can't create resource group and storage in this subscription 'cause you don't have any permissions. 
Ok, I've created the storage inside current resource group called "labvm-97029", but it doesn't make sense since in Task 6, 7 and 8 you won't be able to create “test”, "dev" and "production" environments.

<img width="828" alt="Screenshot 2019-10-05 at 23 43 29" src="https://user-images.githubusercontent.com/19715692/66260655-f5375e00-e7c9-11e9-8f4c-852de3a282b7.png">

In the Task 5 "Create the dev environment and deploy the template to Azure" incorrect path to  azuredeploy.json. azuredeploy.json is located in $HOME/studentfiles/armtemplate after unzipping, but in the guide I found that "Now that the template file has been uploaded" and It's weird because in the task 2 we opened the azuredeploy.json in built-in editor in cloud shell.

**Comment by paulopsgility** [comment]
@masyanru Thanks for the feedback. 

What subscription are you using for this? We don't provide a subscription as part of the lab. If you do not have permissions to create a resource group you will need to talk to the administrator or owner of the subscription. 

I'll update the paths to reflect the unzipped file location.

**Comment by paulopsgility** [comment]
Zip paths issue is a duplicate and has been fixed. The permissions problem isn't specific to the MCW.
