### ISSUE TITLE
Exercise 3, Task 1 - Retain Trigger

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#45]
The final result of the YAML edits are shown in steps 11 and 12 or Exercise 3, Task 1. Neither step displays the build pipeline `trigger`, which had been in place after we selected the pipeline type in step 5. 

If no trigger is defined in the YAML (or from the Triggers tab in the UI), **any code update will trigger a build**. For instance, on creation of a new branch, as in Exercise 6. I don't think it is your intent to remove the trigger on master from the YAML. 

In steps 11 and 12, I recommend that you display at the top of the YAML:
```
trigger:
- master
```
Otherwise, users may assume that it should be removed, even though the instructions do not explicitly say to remove the trigger.

Thanks for listening

**Comment by paulopsgility** [comment]
@snpdev Thanks for the feedback, we will add some clarity around these steps on the next update.
