### ISSUE TITLE
Exercise 1 - Task 4 - Deployment Fails (Wrong Directory)

### ISSUE THREAD

**Issue by AErmie** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#46]
If you follow along with the Before The HOL steps, your Azure Shell prompt directory will be in the studentfiles directory, but your screenshot shows/expects us to be at the root directory and is looking for the azuredeploy.json file in the $HOME directory (which it is not). 

It is actually located in the /studentfiles/armtemplate/ directory. 

You should update the instructions to have the student CD to the right directory, or change the command used to "$HOME/studentfiles/armtemplate/azuredeploy.json"

NOTE: These instructions will also need to be updated for Exercise 1 - Task 5, and Task 6.

**Comment by paulopsgility** [comment]
We'll take care of this during the Nov test/fix
