### ISSUE TITLE
Exercise 2 - Task 2 - GIT Push Fails Due to MFA

### ISSUE THREAD

**Issue by AErmie** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#47]
I've discovered that if I have MFA setup for my Git account, even though I am prompted for the password, I am not prompted for the second factor of authentication. Therefore the Azure Cloud Shell returns a "fatal: Authentication failed" error message. 

As a workaround, if you create a Personal Access Token, this allows the "git push -u origin --all" command to work. 

The instructions should be updated to reflect this potential scenario, and provide alternative steps (ie. Personal Access Token).

**Comment by paulopsgility** [comment]
We'll take care of this during the Nov test/fix
