### ISSUE TITLE
Exercise 5 - Task 1 - Updated Steps Required

### ISSUE THREAD

**Issue by AErmie** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#48]
The instructions for Exercise 5 -  Task 1, no longer match what is displayed in Azure DevOps. 
Instead of the "Queue" button, the button now says "Run pipeline". Also, you no longer see a popup, but rather, a side blade appears, so the screenshot might need to be updated (and ideally in dark mode, as it's hard to see white on white).

**Comment by paulopsgility** [comment]
We'll take care of this during the Nov test/fix
