### ISSUE TITLE
Pipeline Build failed

### ISSUE THREAD

**Issue by inatale** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#50]
Pipeline Build failed due to npm nan module errors:
##[error]clientapp\node_modules\nan\nan_implementation_12_inl.h(103,0): Error C2664: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::ConstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling source file ..\src\binding.cpp) [D:\a\1\s\ClientApp\node_modules\node-sass\build\binding.vcxproj]

**Comment by inatale** [comment]
The following workaround could help:
1. Delete package.json.lock in clientapp folder.
2. Change from rxjs: "^6.0.0" to rxjs: "6.0.0" at package.json in the same folder.

**Comment by paulopsgility** [comment]
@inatale we are looking into this.

**Comment by inatale** [comment]
Thanks. Logs attached if needed.
[logs_67.zip](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/files/3880084/logs_67.zip)

**Comment by paulopsgility** [comment]
@inatale, we are in the process of doing a test/fix on this workshop so we'll correct this during that process.

**Comment by inatale** [comment]
@paulopsgility, thank you a lot.
