### ISSUE TITLE
Issue in Exercise 3: Create Azure DevOps build pipeline

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#51]
In **Exercise 3**, Task 1,  To create Azure DevOps **build** **pipeline** is getting failed with multiple errors.
![image](https://user-images.githubusercontent.com/48020356/69363383-708b9b00-0cb6-11ea-98dc-ed674cd3786a.png)

**Comment by amalgireesh** [comment]
The build got succeeded after deleting the package-lock.json in ClientApp folder and also changing from **rxjs: "^6.0.0"** to rxjs: "6.0.0" at package.json in ClientApp folder,
with reference to https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/issues/50#issuecomment-555739843
![image](https://user-images.githubusercontent.com/48020356/69369639-68395d00-0cc2-11ea-8523-46bb142df6c6.png)

**Comment by amalgireesh** [comment]
Hi @DawnmarieDesJardins ,
We have an upcoming lab, can you please have a quick response on the issue raised.

**Comment by DawnmarieDesJardins** [comment]
@amalgireesh 
Thanks Amal, I've emailed the author to review & advise.

**Comment by amalgireesh** [comment]
@DawnmarieDesJardins Hi,
 Lab is scheduled for 11/27 in Russia.

**Comment by paulopsgility** [comment]
@amalgireesh We are in the middle of a test/fix on this workshop so this will get picked up then. 

It is not going to be ready for 11.27.2019. If you have upcoming deliveries you can fork the repro so you can provide your own workaround.

**Comment by amalgireesh** [comment]
Any updation on this?

**Comment by DawnmarieDesJardins** [comment]
@amalgireesh 
Hi Amal.  The November test/fix has been completed and is ready for QC/merge.  I'm hoping to get this one done today.  When I merger, I'll close out this issue and you'll be notified so you'll know it's done.
