### ISSUE TITLE
Getting Error on Template

### ISSUE THREAD

**Issue by ScottMcF-OneMTC** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#53]
Getting error after updating "Staging" portion of template - 

Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template variable 'webAppName' is not found. Please see https://aka.ms/arm-template/#variables forusage details.'.
Additional Information:
        Type: TemplateViolation
        Info: {
            "lineNumber": 1,
            "linePosition": 3095,
            "path": "properties.template.resources[1].resources[0].dependsOn[0]"

**Comment by scottmcf-EXP-Prod** [comment]
Replaced  "dependsOn": [
        "[resourceId('Microsoft.Web/Sites/', variables('webAppName'))]"
with

parameters('siteName'))]"

and it fixed the issue

**Comment by paulopsgility** [comment]
@scottmcf-EXP-Prod we are looking into this.

**Comment by paulopsgility** [comment]
@scottmcf-EXP-Prod Do you recall at which exercise/task/step you saw this error? I have not been able to reproduce this.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further information from author.  Please reopen if needed.
