### ISSUE TITLE
Continuous Integration step is missing

### ISSUE THREAD

**Issue by andresravinet** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#54]
Continuous Integration step is missing from the HOL page.

**Comment by paulopsgility** [comment]
@andresravinet can you be more specific? Is there something actually missing that prevents you from completing the lab or is this a feature request? In either case we need more information to properly triage this.

**Comment by andresravinet** [comment]
Sure.

At the end of the lab document, it states “Because we configured continuous integration and continuous deployment…” However, nowhere in the lab is there a step to enable CI. My recommendation is to add a step to enable CI or remove that language.


Andres Ravinet
MTC Technical Architect
Microsoft

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Response received, is the what you needed?

**Comment by paulopsgility** [comment]
@andresravinet thanks, we'll resolve this at the next test/fix.

**Comment by paulopsgility** [comment]
This was resolved in the March test/fix
