### ISSUE TITLE
Terraform vs ARM?

### ISSUE THREAD

**Issue by ScottMcF-OneMTC** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#55]
Any plans for creating a Terraform version of this lab/workshop?

**Comment by paulopsgility** [comment]
@ScottMcF-OneMTC  Currently there are no plans to create a Terraform version of this lab. This would probably need to be a whole new lab. This would need to go through the leads for this lab. I'll mark this as an enhancement request for now and we will evaluate at the next update.

**Comment by DawnmarieDesJardins** [comment]
Closing to archive repo.
