### ISSUE TITLE
PostgreSQL admin password requirements

### ISSUE THREAD

**Issue by tylerd** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#57]
Lab participants had difficulty when entering the admin password for the ARM template. The template deployment would fail with a generic message about password complexity, but the complexity requirements are not clear. Specifically the requirement that the password cannot contain 3 or more consecutive characters from the username.

I suggest adding the complexity requirements in the document as a note.

    > **Note**: The password complexity requirements are as follows. *Minimum length 8 characters. Your password must contain characters from three of the following categories – English uppercase letters, English lowercase letters, numbers (0-9), and non-alphanumeric characters (!, $, #, %, etc.). Your password cannot contain all or part of the login name. Part of a login name is defined as three or more consecutive alphanumeric characters*

**Comment by DawnmarieDesJardins** [comment]
@tylerd - Thanks Tyler.  We have a scheduled review of this workshop scheduled soon.  We'll work this and your PR #58 into the review.

**Comment by tylerd** [comment]
Thank you @DawnmarieDesJardins 
I just ran this workshop for a group of about 30 participants and I am going through some of the feedback items. Is this team responsible for the "lab environments" that the participants receive? There are a few issues with the HOL in the lab environment, for example, you can't easily setup the Azure Shell because you don't have the ability to create a storage account for the Subscription, you have to use the Advanced options to create a storage account in the Resource Group that you get with the lab.

**Comment by DawnmarieDesJardins** [comment]
@tylerd - Our authors monitor and respond to open issues left here so this is the perfect place to let us know.  Feel free to look at the current issues and add to them if it fits and open new ones from what you've found in deliveries.  If the changes are complex, we may need to wait for a more in-depth update, but we'll have your info on hand.

**Comment by paulopsgility** [comment]
@tylerd this will get reveiwed for the upcoming test/fix.

**Comment by paulopsgility** [comment]
This was resolved in the March 2020 test fix.
