### ISSUE TITLE
Application Insights missing from the lab material

### ISSUE THREAD

**Issue by thorhj** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#60]
The [abstracts](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps#workshop) has the following paragraph (emphasis mine):

> At the end of this workshop, you will be better able to build templates to automate cloud infrastructure and reduce error-prone manual processes. In addition, you'll create an Azure Resource Manager (ARM) template to provision Azure resources, configure continuous delivery with Azure DevOps, **configure Application Insights into an application**, and create an Azure DevOps project and Git repository.

I have gone through the lab in preparation, and I have seen nothing about Application Insights in the lab material. Has the scope of the workshop changed to no longer include Application Insights, or is something missing from the lab material?

**Comment by paulopsgility** [comment]
@thorhj No, the scope has not changed. Application Insights is part of the whiteboard design session. Not everything covered in the WDS makes it into the lab.
