### ISSUE TITLE
Need to update instruction for exercise 1 task 4 step 1

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#63]
Hi, 

A note to be added for students to use existing RG if they don't have permissions to create the new resource group in [Exercise 1 task 4.1](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-4-create-the-dev-environment-and-deploy-the-template-to-azure). We don't want to allow lab attendees to create a new resource group for **Cloudlabs** ODLs.

And 
In [Exercise 4, task 1, step 30](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-1-create-a-release-definition) can we update the screenshot and instruction to select the subscription first and then the resource group, if lab attendee only have resource group level permissions.

**Comment by paulopsgility** [comment]
@akn9050 We write the labs to work in generic subscriptions. We do this because most consumers of the lab will be using a generic subscription and we cannot account for all of the various customizations and limitations that different environments might have.

**Comment by akn9050** [comment]
@paulopsgility , I completely agree with you, if you can add just one line note at both the steps. Without any screenshots also, it will help a lot for the folks who is not exposing subscription level permissions.

Thanks

**Comment by paulopsgility** [comment]
@akn9050 It is our policy to write labs to generic subscriptions so I am not going to be able to add notes for all the various issues that people might encounter based on configuration issues outside of our control so I am going to close this out.
