### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by paulopsgility** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#64]
Here are our suggested updates for the June 2020 update. Please add any other suggestions or feedback to this issue.

- Update diagrams to use modern Azure icons
- YAML Based Release Pipeline update (issue #33)
- Update to use a single resource group / service connection to allow lab to be run without requiring owner role in the subscription

**Comment by gidavies** [comment]
A suggestion: In Exercise 6: Setup a pull request policy, create a task branch and submit a pull request, create the new branch from a card in Azure Boards? This might add a few more steps to create a work item but it will then show a more complete branch created from and linked to a work item.

**Comment by paulopsgility** [comment]
@gidavies I think that is a good idea. We'll add that as well.

**Comment by DawnmarieDesJardins** [comment]
Closing update issue with merge of PR #65
