### ISSUE TITLE
Pipeline triggered after commit on the new-heading branch

### ISSUE THREAD

**Issue by StevenHanquez** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#66]
Thank you for this excellent guide. However, despite having scrupulously followed the indicated steps, I have a strange behavior on one of the exercise.

In Exercise 6 (Setup a pull request policy, create a task branch and submit a pull request), Task 3, Step 3, I do a commit after change the home.compenent.html in the new-heading branch.

For some reason that I don't understand, this commit caused the pipeline to run and, therefore, the deployment to Dev, Test, and Production environments.

![image](https://user-images.githubusercontent.com/5033972/90963536-a3b6c100-e4b8-11ea-989f-abf514c6ceda.png)

Normally (if I understood correctly) this should only have happened when merging with the master branch (after completed the pull request).

Did I miss a step?

**Comment by DawnmarieDesJardins** [comment]
@mwasham @SimonOpsgilityNeale 
Please review & advise.

**Comment by SimonOpsgilityNeale** [comment]
@DawnmarieDesJardins We currently have one of the team looking into this and we will share feedback once we know more.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #67 and ran HTML script.
