### ISSUE TITLE
Application Insights 

### ISSUE THREAD

**Issue by mariuszdotnet** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#68]
![image](https://user-images.githubusercontent.com/1854283/96006874-ef784d80-0e0b-11eb-95ed-3c16b47a5e08.png)

Application Insights is mentioned as part of the LAB but the actual lad does not have that part it in.  Should the description be updated and or the LAB content.

**Comment by DawnmarieDesJardins** [comment]
@mariuszdotnet 
Thank you for the heads up Mariusz!  I've updated the ReadMe page abstract to match the lab document.

@jtuliani 
Jonathan, please review the ReadMe page to verify everything is correct and matches the June 2020 updates.  Follow up with the update author to advise the miss.

**Comment by jtuliani** [comment]
App Insights is included in the WDS, but not in the HOL. I'll update.
