### ISSUE TITLE
There is an Error in EX4\Task1. 

### ISSUE THREAD

**Issue by saeinc** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#69]
I've done all of processes in this HOL but there is an error in Ex4 - Task 1. 

I've done code change, indentation, and component addition all as guided, but errors occur when running the last pipeline, and the error is as follows.
"/azure-pipelines.yml (Line:22, Col:1): Unexpected value 'steps'" 

I think there are more code in 'steps' section but there are no guidance for this. 

For your reference, I'm attaching a final virsion of code as text. 

# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'
      demands:
      - msbuild
      - visualstudio
      - vstest

steps:
# Nuget Tool Installer Task
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

# Node.js Tool Installer Task
# Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
- task: NodeTool@0
  inputs:
    versionSpec: '10.x' 

# Nuget Restore Task
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**/tailspintoysweb.csproj'

# Build Task  
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/tailspintoysweb.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
    platform: 'any cpu'
    configuration: 'release'

# Publish Task
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: succeededOrFailed()

- stage: DevDeploy
  displayName: 'Dev Deploy Stage'
  jobs:
  - job: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted VS2017
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(Build.ArtifactStagingDirectory'
        artifactName: 'drop'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'LabConnection'
    appType: 'webApp'
    WebAppName: 'tailspintoys-dev-3ykmhcbmzxvfc'
    deployToSlotOrASE: true
    ResourceGroupName: 'TailSpinToysRG'
    SlotName: 'staging'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

**Comment by dwnatwick** [comment]
@saeinc. We are looking into the issue and hope to have a fix for it some time next week.  Thank you very much for bringing it to our attention.

**Comment by blgorman** [comment]
@saeinc 
Please note that the line at the beginning of step 3 states
"highlight the remainder of the YAML file that defines your build jobs and indent it four spaces (two tabs), thus making this definition a child of the build stage *jobs* node."

It appears you did not highlight the rest of the file and indent appropriately.  
![yaml](https://user-images.githubusercontent.com/785214/99120303-42d2ec80-25c0-11eb-8f53-d213970c07fa.png)

Make sure that "steps" has its "s" under the "p" in pool.
Make sure that each task under steps has the "-" under the s and then the rest of the indents map.

**Comment by blgorman** [comment]
For more clarity, I used the DevOps pipeline and have collapsed sections from the final YAML so you can reference this.  If you can't collapse like this, then the YAML is not spaced correctly.

![pipelinecollapsed](https://user-images.githubusercontent.com/785214/99121485-0ef8c680-25c2-11eb-86d4-6408eea0e723.png)

**Comment by opsgilitybrian** [comment]
@DawnmarieDesJardins @mwasham @dwnatwick 
Please see PR #70 to add clarity to the text regarding the spacing for the YAML
