### ISSUE TITLE
There is no linked work items in Ex6. 

### ISSUE THREAD

**Issue by saeinc** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#71]
In Ex6-Task1, when I set the branch policy, "Check for linked work items" is enabled as required option. 
and then when I tried to submit a pull request, there is no work items to link so I got an red sign in "Task 5-step 1" as attached. 
However, There is no linked work item in task 3-step 5. So after submitting a pull request, there is an red sign. 
Is it okay?

**Comment by opsgilitybrian** [comment]
Hello @saeinc -

At one point I believe that the project used for this came with a bunch of pre-created work items.  For this, you should just create your own to track.  If you don't want to do that, you could just not enable the policy that requires a tracked work item.

I have added a step to the documentation for creating a simple work item to track, but really you can just create any work item on the azure boards for your project and associate it, and you would be good to go.  Thanks for bringing this up.
