### ISSUE TITLE
June 2021 Suggested Updates

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#82]
Eliminate ARM template specific Exercise 1

- Establish prewritten ARM templates in another repository alongside app repository
- Create IaC build and/or release pipelines
- Use ADO variable groups to parameterize build and/or release pipelines for DEV/TEST/PROD environments 
- Effectively becomes first half of lab focused on Infrastructure deployment pipelines in ADO

Regarding Question 6
- Option 1 – Use Azure DevOps repositories
  Relatively few, if any, changes

- Option 2 – Change to use Github repositories
 Will require almost complete rewrite of exercise 6
   Operations around pull request and branching policies may require exclusive management in Github, completely changing steps
   Navigation between ADO and Github may be confusing/disorienting to students
   Unsure of current level of integration between ADO and Github that already exists with ADO repositories

**Comment by DawnmarieDesJardins** [comment]
@hatboyzero 
Please see field PR #84 during this update

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of update PR
